-- Seed data for development and testing
-- This file is run after migrations to populate initial data

-- Insert sample user profile (requires auth.users to exist first)
-- You would typically create this through the Supabase Auth flow

-- Sample AI Agents
INSERT INTO public.agents (id, user_id, name, type, status, configuration, capabilities) VALUES
  (
    '00000000-0000-0000-0000-000000000001',
    auth.uid(), -- Current user
    'Task Manager',
    'task_manager',
    'active',
    '{"auto_prioritize": true, "suggest_breakdowns": true}'::jsonb,
    ARRAY['task_creation', 'prioritization', 'scheduling']
  ),
  (
    '00000000-0000-0000-0000-000000000002',
    auth.uid(),
    'Workflow Orchestrator',
    'workflow_engine',
    'active',
    '{"max_concurrent_workflows": 10}'::jsonb,
    ARRAY['workflow_execution', 'state_management', 'condition_evaluation']
  ),
  (
    '00000000-0000-0000-0000-000000000003',
    auth.uid(),
    'Research Assistant',
    'researcher',
    'active',
    '{"search_depth": "thorough", "summarize": true}'::jsonb,
    ARRAY['web_search', 'document_analysis', 'summarization']
  );

-- Sample Workflow Templates
INSERT INTO public.workflows (id, user_id, name, description, status, trigger_type, trigger_config) VALUES
  (
    '10000000-0000-0000-0000-000000000001',
    auth.uid(),
    'Daily Task Review',
    'Automatically review and prioritize tasks every morning',
    'active',
    'scheduled',
    '{"schedule": "0 9 * * *", "timezone": "UTC"}'::jsonb
  ),
  (
    '10000000-0000-0000-0000-000000000002',
    auth.uid(),
    'Email-to-Task Converter',
    'Convert important emails into actionable tasks',
    'draft',
    'event',
    '{"event_type": "email_received", "filters": {"importance": "high"}}'::jsonb
  );

-- Sample Tasks
INSERT INTO public.tasks (id, user_id, workflow_id, title, description, status, priority, due_date) VALUES
  (
    '20000000-0000-0000-0000-000000000001',
    auth.uid(),
    NULL,
    'Set up Joanna AI Assistant',
    'Complete the initial setup and configuration of the Joanna personal AI assistant',
    'in_progress',
    1,
    NOW() + INTERVAL '3 days'
  ),
  (
    '20000000-0000-0000-0000-000000000002',
    auth.uid(),
    NULL,
    'Review workflow automation options',
    'Explore different workflow automation patterns for daily operations',
    'todo',
    2,
    NOW() + INTERVAL '1 week'
  ),
  (
    '20000000-0000-0000-0000-000000000003',
    auth.uid(),
    '10000000-0000-0000-0000-000000000001',
    'Test daily task review workflow',
    'Verify that the automated daily task review works correctly',
    'todo',
    3,
    NOW() + INTERVAL '2 weeks'
  );

-- Sample Knowledge Items
INSERT INTO public.knowledge_items (id, user_id, type, title, content, tags) VALUES
  (
    '30000000-0000-0000-0000-000000000001',
    auth.uid(),
    'note',
    'Getting Started with Joanna',
    'Joanna is designed to be your intelligent personal assistant. Start by defining your workflows and letting the AI agents help automate your tasks.',
    ARRAY['onboarding', 'guide']
  ),
  (
    '30000000-0000-0000-0000-000000000002',
    auth.uid(),
    'reference',
    'Best Practices for Workflow Design',
    'When designing workflows: 1) Keep states simple and focused, 2) Use clear transition conditions, 3) Handle error states, 4) Test thoroughly before activation.',
    ARRAY['workflows', 'best-practices']
  );

-- Note: Embeddings would be generated by your application code using OpenAI/Anthropic
-- and updated separately via your Edge Functions
